/**
 * Catalogue de référence des rubriques de l'application.
 * Sert à remplir automatiquement le registre `app_features` (guide d'utilisation).
 * Ajout uniquement : rien ici ne modifie une rubrique existante.
 */

export type FeatureLink = { to: string; kind: "envoie vers" | "reçoit de" | "notifie" };

export type FeatureSeed = {
  route: string;
  name: string;
  category: string;
  description: string;
  child_explanation: string;
  purpose: string;
  how_to: string;
  owner_positions: string[];
  collaborator_positions: string[];
  links: FeatureLink[];
  sort_order: number;
};

const TBC = "à confirmer par le Producteur général";

export const FEATURE_CATALOG: FeatureSeed[] = [
  {
    route: "/dashboard",
    name: "Tableau de bord",
    category: "Pilotage",
    description:
      "C'est la première page après la connexion. Elle rassemble en un coup d'œil vos tâches, vos rapports, les projets du club et les nouveautés.",
    child_explanation:
      "C'est comme le tableau d'affichage de la classe : on y voit tout de suite ce qu'il faut faire aujourd'hui.",
    purpose: "Voir l'essentiel sans chercher dans toutes les rubriques.",
    how_to:
      "1. Connectez-vous. 2. Regardez les cartes affichées. 3. Cliquez sur une carte pour ouvrir la rubrique complète.",
    owner_positions: ["Producteur général"],
    collaborator_positions: ["Tous les membres"],
    links: [
      { to: "/taches", kind: "envoie vers" },
      { to: "/projets-approuves", kind: "envoie vers" },
      { to: "/idees", kind: "reçoit de" },
    ],
    sort_order: 10,
  },
  {
    route: "/taches",
    name: "Mes tâches",
    category: "Travail",
    description:
      "La liste du travail confié à chaque personne, avec une date limite et un état (à faire, en cours, terminé).",
    child_explanation: "C'est la liste des devoirs : on coche quand c'est fini.",
    purpose: "Savoir qui fait quoi et pour quand.",
    how_to:
      "1. Ouvrez « Mes tâches ». 2. Ouvrez une tâche. 3. Changez son état ou envoyez le résultat avec un lien.",
    owner_positions: ["Producteur général", "Producteur délégué"],
    collaborator_positions: ["Tous les membres"],
    links: [
      { to: "/rapports", kind: "envoie vers" },
      { to: "/dashboard", kind: "notifie" },
    ],
    sort_order: 20,
  },
  {
    route: "/rapports",
    name: "Rapports",
    category: "Travail",
    description:
      "Chaque membre raconte ce qu'il a fait ; le responsable lit, commente et valide.",
    child_explanation: "C'est le cahier où on écrit ce qu'on a fait, et le maître le signe.",
    purpose: "Garder une trace du travail réalisé et le faire valider.",
    how_to: "1. Cliquez sur « Nouveau rapport ». 2. Écrivez. 3. Envoyez au responsable.",
    owner_positions: ["Producteur général", "Producteur délégué"],
    collaborator_positions: ["Tous les membres"],
    links: [
      { to: "/taches", kind: "reçoit de" },
      { to: "/analyse", kind: "envoie vers" },
    ],
    sort_order: 30,
  },
  {
    route: "/conges",
    name: "Mes congés",
    category: "Travail",
    description:
      "On demande une absence, on dit pourquoi et quand on revient ; le responsable accepte ou refuse.",
    child_explanation: "C'est le mot pour dire « je serai absent », et on attend la réponse.",
    purpose: "Organiser les absences sans bloquer le travail des autres.",
    how_to: "1. Indiquez les dates et le motif. 2. Envoyez. 3. Attendez la réponse, qui vous est notifiée.",
    owner_positions: ["Producteur général", "Producteur délégué"],
    collaborator_positions: ["Tous les membres"],
    links: [{ to: "/dashboard", kind: "notifie" }],
    sort_order: 40,
  },
  {
    route: "/equipes",
    name: "Équipes",
    category: "Organisation",
    description: "Les groupes de travail du club, avec un responsable et ses membres.",
    child_explanation: "C'est comme les équipes au sport : chacun sait dans quel groupe il joue.",
    purpose: "Réunir les bonnes personnes autour d'un même travail.",
    how_to: "1. Créez une équipe. 2. Ajoutez des membres. 3. Choisissez le responsable.",
    owner_positions: ["Producteur général"],
    collaborator_positions: ["Producteur délégué", "Réalisateur"],
    links: [{ to: "/organigramme", kind: "envoie vers" }],
    sort_order: 50,
  },
  {
    route: "/organigramme",
    name: "Organigramme",
    category: "Organisation",
    description: "L'arbre du club : qui dirige qui, et le poste de chacun avec sa description.",
    child_explanation: "C'est l'arbre généalogique du club : on voit qui est au-dessus de qui.",
    purpose: "Comprendre les responsabilités d'un coup d'œil.",
    how_to: "1. Ouvrez l'organigramme. 2. Cliquez sur une personne pour voir sa fiche.",
    owner_positions: ["Producteur général"],
    collaborator_positions: ["Tous les membres"],
    links: [{ to: "/membres", kind: "reçoit de" }],
    sort_order: 60,
  },
  {
    route: "/membres",
    name: "Membres",
    category: "Organisation",
    description: "La liste des personnes du club, avec leur poste, leur email et leur description.",
    child_explanation: "C'est le carnet d'adresses de la classe.",
    purpose: "Créer un compte, changer un poste ou corriger une adresse email.",
    how_to: "1. Ouvrez la fiche d'un membre. 2. Modifiez le champ voulu. 3. Enregistrez.",
    owner_positions: ["Producteur général"],
    collaborator_positions: ["Producteur délégué"],
    links: [
      { to: "/organigramme", kind: "envoie vers" },
      { to: "/equipes", kind: "envoie vers" },
    ],
    sort_order: 65,
  },
  {
    route: "/ressources",
    name: "Liens & documents",
    category: "Communication",
    description: "Les documents utiles du club rangés au même endroit, avec leur lien.",
    child_explanation: "C'est le cartable commun : tout le monde y range ses feuilles.",
    purpose: "Retrouver un document sans le chercher partout.",
    how_to: "1. Ajoutez un titre et un lien. 2. Choisissez une catégorie. 3. Enregistrez.",
    owner_positions: ["Producteur général"],
    collaborator_positions: ["Tous les membres"],
    links: [],
    sort_order: 70,
  },
  {
    route: "/discussion",
    name: "Discussions",
    category: "Communication",
    description: "Les échanges de groupe du club, par sujet ou par projet.",
    child_explanation: "C'est la discussion en récréation, mais écrite.",
    purpose: "Parler à plusieurs et garder une trace des décisions.",
    how_to: "1. Ouvrez une discussion. 2. Écrivez votre message. 3. Envoyez.",
    owner_positions: ["Producteur général"],
    collaborator_positions: ["Tous les membres"],
    links: [{ to: "/messagerie", kind: "notifie" }],
    sort_order: 80,
  },
  {
    route: "/messagerie",
    name: "Messagerie",
    category: "Communication",
    description: "Les messages privés entre deux personnes, avec notification et indicateur « vu ».",
    child_explanation: "C'est un petit mot glissé à une seule personne.",
    purpose: "Échanger directement sans déranger tout le groupe.",
    how_to: "1. Choisissez la personne. 2. Écrivez. 3. Envoyez.",
    owner_positions: ["Producteur général"],
    collaborator_positions: ["Tous les membres"],
    links: [{ to: "/dashboard", kind: "notifie" }],
    sort_order: 90,
  },
  {
    route: "/reunions",
    name: "Réunions vidéo",
    category: "Communication",
    description: "Les rendez-vous en ligne du club, avec leur lien et leur heure.",
    child_explanation: "C'est le rendez-vous où tout le monde se voit par l'écran.",
    purpose: "Se réunir même à distance.",
    how_to: "1. Créez la réunion. 2. Collez le lien vidéo. 3. Partagez le lien public.",
    owner_positions: ["Producteur général", "Producteur délégué"],
    collaborator_positions: ["Tous les membres"],
    links: [],
    sort_order: 100,
  },
  {
    route: "/idees",
    name: "Idées & projets",
    category: "Projets",
    description:
      "Les dossiers reçus, internes ou externes, avec leur numéro (CT-AAAA-000) et leur avancement, du dépôt jusqu'à la réponse.",
    child_explanation: "C'est la boîte où on met les idées de films, et on suit ce qu'elles deviennent.",
    purpose: "Recevoir, étudier et répondre à chaque idée sans en perdre une.",
    how_to:
      "1. Ouvrez un dossier. 2. Lisez son contenu et ses liens. 3. Donnez votre avis, répondez ou approuvez.",
    owner_positions: ["Producteur général", "Producteur délégué", "Scénariste"],
    collaborator_positions: ["Réalisateur"],
    links: [
      { to: "/projets-approuves", kind: "envoie vers" },
      { to: "/suivi-dossier", kind: "envoie vers" },
    ],
    sort_order: 110,
  },
  {
    route: "/nouveau-projet",
    name: "Déposer un projet",
    category: "Projets",
    description:
      "Le formulaire pour proposer un projet : titre, logline, synopsis, notes et scénario, en texte ou en lien Google.",
    child_explanation: "C'est la feuille où on raconte son idée de film pour la proposer au club.",
    purpose: "Permettre à chaque membre de proposer un projet, même hors vote.",
    how_to: "1. Remplissez les cases. 2. Ajoutez vos liens. 3. Envoyez : le comité est prévenu.",
    owner_positions: ["Producteur général", "Producteur délégué", "Réalisateur", "Scénariste"],
    collaborator_positions: ["Tous les membres"],
    links: [{ to: "/projets-approuves", kind: "envoie vers" }],
    sort_order: 120,
  },
  {
    route: "/projets-approuves",
    name: "Projets approuvés",
    category: "Projets",
    description:
      "Les projets retenus par le club, internes ou externes, avec leur équipe, leur phase et leur délai.",
    child_explanation: "Ce sont les idées qui sont devenues de vrais films en préparation.",
    purpose: "Suivre l'avancement réel de chaque film du club.",
    how_to: "1. Choisissez un projet. 2. Regardez sa phase et son délai. 3. Le Producteur général peut les changer.",
    owner_positions: ["Producteur général", "Producteur délégué"],
    collaborator_positions: ["Réalisateur", "Scénariste"],
    links: [
      { to: "/budget-previsionnel", kind: "envoie vers" },
      { to: "/comptabilite", kind: "envoie vers" },
      { to: "/dashboard", kind: "notifie" },
    ],
    sort_order: 130,
  },
  {
    route: "/budget-previsionnel",
    name: "Budget prévisionnel",
    category: "Argent",
    description:
      "La liste de ce qu'un projet va coûter : catégorie, libellé, quantité, prix, total calculé tout seul.",
    child_explanation: "C'est la liste de courses avant d'aller au marché.",
    purpose: "Prévoir les dépenses avant de les faire.",
    how_to: "1. Choisissez un projet approuvé. 2. Ajoutez vos lignes. 3. Le total se calcule automatiquement.",
    owner_positions: ["Comptable / Trésorier", "Producteur général", "Producteur délégué"],
    collaborator_positions: [
      "Réalisateur",
      "Régisseur général",
      "Accessoiriste",
      "Directeur artistique / Chef décorateur",
      "Chef opérateur (Directeur de la photographie)",
      "Scénariste",
    ],
    links: [{ to: "/comptabilite", kind: "envoie vers" }],
    sort_order: 140,
  },
  {
    route: "/comptabilite",
    name: "Comptabilité",
    category: "Argent",
    description:
      "Les dépenses réellement faites, rattachées à un projet, comparées au budget prévu.",
    child_explanation: "C'est le carnet où on note l'argent dépensé pour de vrai.",
    purpose: "Voir où va l'argent et si l'on respecte le budget.",
    how_to: "1. Ajoutez une dépense. 2. Choisissez le projet. 3. Enregistrez.",
    owner_positions: ["Comptable / Trésorier", "Producteur général"],
    collaborator_positions: ["Producteur délégué"],
    links: [{ to: "/budget-previsionnel", kind: "reçoit de" }],
    sort_order: 150,
  },
  {
    route: "/analyse",
    name: "Analyse de travail",
    category: "Pilotage",
    description: "Un résumé chiffré du travail : tâches faites, rapports envoyés, retards.",
    child_explanation: "C'est le bulletin qui montre comment avance le travail du club.",
    purpose: "Repérer ce qui avance bien et ce qui bloque.",
    how_to: "1. Ouvrez la page. 2. Lisez les chiffres. 3. Agissez sur les retards.",
    owner_positions: ["Producteur général"],
    collaborator_positions: ["Producteur délégué"],
    links: [{ to: "/rapports", kind: "reçoit de" }],
    sort_order: 160,
  },
  {
    route: "/contrats",
    name: "Contrats",
    category: "Organisation",
    description: "Les engagements écrits avec les personnes : rôle, durée, montant, statut.",
    child_explanation: "C'est la promesse écrite entre le club et une personne.",
    purpose: "Garder une trace claire de chaque engagement.",
    how_to: "1. Créez un contrat. 2. Remplissez les conditions. 3. Enregistrez et téléchargez le PDF.",
    owner_positions: ["Producteur général", "Producteur délégué"],
    collaborator_positions: ["Comptable / Trésorier"],
    links: [],
    sort_order: 170,
  },
  {
    route: "/feuille-de-service",
    name: "Feuille de service",
    category: "Tournage",
    description: "Le programme d'une journée de tournage : heure, lieu, équipe convoquée, notes.",
    child_explanation: "C'est l'emploi du temps du jour de tournage.",
    purpose: "Que chacun sache où et quand se présenter.",
    how_to: "1. Créez la feuille. 2. Choisissez l'équipe dans la liste. 3. Téléchargez le PDF et partagez-le.",
    owner_positions: ["Régisseur général", "Producteur délégué"],
    collaborator_positions: ["Réalisateur", "Tous les membres"],
    links: [{ to: "/projets-approuves", kind: "reçoit de" }],
    sort_order: 180,
  },
  {
    route: "/festivals",
    name: "Festivals",
    category: "Diffusion",
    description: "Les festivals et appels à films, avec leur date limite et leur lien.",
    child_explanation: "C'est la liste des concours où l'on peut montrer nos films.",
    purpose: "Ne rater aucune date d'inscription.",
    how_to: "1. Ajoutez le festival. 2. Notez la date limite. 3. Suivez la liste.",
    owner_positions: ["Producteur général"],
    collaborator_positions: ["Réalisateur"],
    links: [],
    sort_order: 190,
  },
  {
    route: "/vote",
    name: "Vote",
    category: "Projets",
    description:
      "Les votes du club pour choisir un projet, avec accès par code et résultats ; le gagnant devient un projet interne.",
    child_explanation: "C'est l'élection du délégué de classe, mais pour choisir un film.",
    purpose: "Décider ensemble, de façon claire et traçable.",
    how_to: "1. Créez la session. 2. Ajoutez les projets. 3. Ouvrez, puis clôturez et proclamez.",
    owner_positions: ["Producteur général"],
    collaborator_positions: ["Producteur délégué", "Tous les membres"],
    links: [{ to: "/projets-approuves", kind: "envoie vers" }],
    sort_order: 200,
  },
  {
    route: "/casting",
    name: "Casting",
    category: "Tournage",
    description: "Les appels à comédiens, le lien public de candidature et les candidatures reçues.",
    child_explanation: "C'est l'annonce pour trouver les acteurs du film.",
    purpose: "Recevoir et trier les candidatures au même endroit.",
    how_to: "1. Créez l'appel. 2. Partagez le lien public. 3. Acceptez ou refusez chaque candidature.",
    owner_positions: ["Producteur général", "Réalisateur"],
    collaborator_positions: ["Producteur délégué"],
    links: [{ to: "/casting-soumission", kind: "reçoit de" }],
    sort_order: 210,
  },
  {
    route: "/archives",
    name: "Archives du club",
    category: "Mémoire",
    description: "La mémoire du club : votes clôturés, dossiers et documents conservés.",
    child_explanation: "C'est la boîte à souvenirs du club.",
    purpose: "Retrouver plus tard ce qui a été fait.",
    how_to: "1. Ouvrez les archives. 2. Choisissez une catégorie. 3. Consultez.",
    owner_positions: ["Producteur général"],
    collaborator_positions: ["Tous les membres"],
    links: [{ to: "/vote", kind: "reçoit de" }],
    sort_order: 220,
  },
  {
    route: "/mentors",
    name: "Mentors externes",
    category: "Accompagnement",
    description:
      "Les liens d'invitation donnés aux mentors, et les échanges avec eux ; ils voient les projets en lecture seule.",
    child_explanation: "C'est le grand frère qui vient conseiller, mais qui ne touche à rien.",
    purpose: "Être conseillé par des professionnels sans ouvrir les données internes.",
    how_to: "1. Créez une invitation. 2. Envoyez le lien. 3. Répondez à ses messages.",
    owner_positions: ["Producteur général", "Producteur délégué"],
    collaborator_positions: [],
    links: [{ to: "/mentor-espace", kind: "envoie vers" }],
    sort_order: 230,
  },
  {
    route: "/journal",
    name: "Journal d'activité",
    category: "Pilotage",
    description: "La trace de ce qui se passe dans l'application : qui a fait quoi et quand.",
    child_explanation: "C'est le cahier de bord : tout ce qui s'est passé y est écrit.",
    purpose: "Comprendre l'historique et garder la transparence.",
    how_to: "1. Ouvrez le journal. 2. Parcourez les entrées récentes.",
    owner_positions: ["Producteur général"],
    collaborator_positions: [],
    links: [],
    sort_order: 240,
  },
  {
    route: "/modifications",
    name: "Modifications",
    category: "Pilotage",
    description:
      "L'espace de réglages du Producteur général : postes, phases, messages, comptes, e-mails, corbeille, base de données, guide.",
    child_explanation: "C'est la salle des boutons : on y règle comment fonctionne l'application.",
    purpose: "Adapter l'application au club sans refaire le logiciel.",
    how_to: "1. Ouvrez « Modifications ». 2. Choisissez un onglet. 3. Modifiez puis enregistrez.",
    owner_positions: ["Producteur général"],
    collaborator_positions: [],
    links: [
      { to: "/dashboard", kind: "notifie" },
      { to: "/journal", kind: "envoie vers" },
    ],
    sort_order: 250,
  },
  {
    route: "/espace-bailleur",
    name: "Mon espace bailleur",
    category: "Argent",
    description:
      "L'espace réservé aux bailleurs : leurs contributions et le suivi des projets qu'ils soutiennent, en lecture seule.",
    child_explanation: "C'est la fenêtre par laquelle celui qui aide voit ce que devient son aide.",
    purpose: "Montrer aux bailleurs, en toute transparence, l'usage de leur soutien.",
    how_to: "1. Connectez-vous avec le compte bailleur. 2. Consultez les contributions et les projets.",
    owner_positions: ["Producteur général", "Comptable / Trésorier"],
    collaborator_positions: [],
    links: [{ to: "/comptabilite", kind: "reçoit de" }],
    sort_order: 260,
  },
  {
    route: "/mot-de-passe",
    name: "Mot de passe oublié",
    category: "Comptes",
    description: "Les demandes d'aide pour se reconnecter, traitées par le Producteur général.",
    child_explanation: "C'est quand on a perdu la clé et qu'on demande une nouvelle.",
    purpose: "Aider un membre bloqué à revenir dans l'application.",
    how_to: "1. Le membre fait la demande. 2. Le Producteur général répond et réinitialise.",
    owner_positions: ["Producteur général", "Producteur délégué"],
    collaborator_positions: [],
    links: [{ to: "/modifications", kind: "envoie vers" }],
    sort_order: 270,
  },
  {
    route: "/idees-soumission",
    name: "Dépôt public d'une idée",
    category: "Public",
    description: "La page ouverte à tous, sans compte, pour envoyer une idée de film au club.",
    child_explanation: "C'est la boîte aux lettres devant la porte du club.",
    purpose: "Recevoir des idées venues de l'extérieur.",
    how_to: "1. Remplissez le formulaire. 2. Ajoutez vos liens Google. 3. Envoyez et notez votre numéro de dossier.",
    owner_positions: ["Producteur général"],
    collaborator_positions: ["Scénariste"],
    links: [{ to: "/idees", kind: "envoie vers" }],
    sort_order: 280,
  },
  {
    route: "/suivi-dossier",
    name: "Suivi d'un dossier",
    category: "Public",
    description: "La page qui permet à un auteur externe de suivre son dossier avec son lien unique.",
    child_explanation: "C'est le numéro de suivi d'un colis : on regarde où il en est.",
    purpose: "Informer l'auteur sans lui créer de compte.",
    how_to: "1. Ouvrez le lien reçu. 2. Regardez l'étape en cours.",
    owner_positions: ["Producteur général"],
    collaborator_positions: [],
    links: [{ to: "/idees", kind: "reçoit de" }],
    sort_order: 290,
  },
  {
    route: "/mentor-espace",
    name: "Espace mentor externe",
    category: "Accompagnement",
    description:
      "L'espace du mentor invité : projets en cours, phase et logline en lecture seule, plus un fil de discussion.",
    child_explanation: "C'est la salle d'à côté : le mentor voit le film se préparer, sans rien changer.",
    purpose: "Recevoir des conseils extérieurs en protégeant les données internes.",
    how_to: "1. Ouvrez le lien d'invitation. 2. Consultez les projets. 3. Écrivez au club.",
    owner_positions: ["Producteur général", "Producteur délégué"],
    collaborator_positions: [],
    links: [{ to: "/mentors", kind: "notifie" }],
    sort_order: 300,
  },
  {
    route: "/guide",
    name: "Guide d'utilisation",
    category: "Pilotage",
    description:
      "Le mode d'emploi du logiciel, construit automatiquement à partir du registre des rubriques et téléchargeable en PDF.",
    child_explanation: "C'est la notice du jeu : elle explique comment on joue, avec des mots faciles.",
    purpose: "Que chacun comprenne l'application sans formation.",
    how_to: "1. Ouvrez « Modifications ». 2. Onglet « Guide d'utilisation ». 3. Téléchargez le PDF.",
    owner_positions: ["Producteur général"],
    collaborator_positions: ["Tous les membres"],
    links: [{ to: "/modifications", kind: "reçoit de" }],
    sort_order: 310,
  },
  {
    route: "/dossier-presentation",
    name: "Dossier de présentation du logiciel",
    category: "Pilotage",
    description:
      "Deux dossiers PDF, un pour les bailleurs et un pour les membres, pour présenter le logiciel et le club.",
    child_explanation: "C'est l'affiche qui explique pourquoi notre outil est utile.",
    purpose: "Présenter et défendre le logiciel auprès des partenaires.",
    how_to: "1. Ouvrez « Modifications ». 2. Onglet « Dossier de présentation ». 3. Modifiez les textes et téléchargez.",
    owner_positions: ["Producteur général"],
    collaborator_positions: [],
    links: [{ to: "/guide", kind: "reçoit de" }],
    sort_order: 320,
  },
];

export const TO_CONFIRM = TBC;
